# This yaml file is used to run the database before running the application for testing
version: '3'

services:

  mysql_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - /var/lib/docker/volumes/devops-project-volume/_data:/var/lib/mysql
