version: '3'

services:

  mysql_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sofiene #${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=pet_store #${MYSQLDB_DATABASE}
    ports:
      #${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
      - "3306:3306"
    volumes:
      - /var/lib/docker/volumes/devops-project-volume/_data:/var/lib/mysql

  backend-app:
    image: sofienechihi/my-repo:spring-app-1.0
    restart: on-failure
    depends_on:
      - mysql_db
    ports:
      # ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - "8080:8080"
    environment:
      - DATABASE_HOST=mysql_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=sofiene
      - DATABASE_NAME=pet_store
      - DATABASE_PORT=3306
